/**
 * Prontidão da IDENTIDADE do consultor.
 *
 * Regra de produto: tudo que o lead ouve/lê tem que ser 100% do consultor
 * (nome dele + nome da IA dele). Nada de herdar áudio de outro dono.
 *
 * Este módulo só LÊ o estado e devolve, em linguagem de leigo, o que falta
 * e como resolver. A geração em si é a edge `consultant-identity-bootstrap`.
 */
import { supabase } from "@/integrations/supabase/client";
import { validateBrazilPhone } from "@/lib/phone";

/** Etapas de ligação que precisam de corpo com a voz/identidade do consultor. */
export const IDENTITY_CALL_STAGES = [
  "A_CALL",
  "A_CALL_RETRY",
  "CALL_1",
  "CALL_2",
  "CALL_3",
  "RECALL_60D_CALL",
  "RECALL_90D_CALL",
  "RECALL_5M_CALL",
  "RECALL_8M_CALL",
  "RECALL_12M_CALL",
  "RECALL_YEARLY_CALL",
] as const;

export type IdentityStepId =
  | "nome"
  | "ia"
  | "genero"
  | "telefone"
  | "whatsapp"
  | "a2"
  | "ligacoes";

export type IdentityStep = {
  id: IdentityStepId;
  /** Nome curto que o consultor entende. */
  title: string;
  /** Por que isso importa (1 linha). */
  why: string;
  /** Passo a passo para leigo. */
  how: string;
  done: boolean;
  /** Precisa estar pronto ANTES de gerar os áudios. */
  prerequisite: boolean;
  /** Resolvido automaticamente pelo botão "Gerar tudo". */
  autoGenerated: boolean;
  /** Ex.: "7 de 11 prontos". */
  progressLabel?: string;
};

export type IdentityStatus = {
  consultantId: string;
  consultorLabel: string;
  assistantName: string;
  steps: IdentityStep[];
  /** Faltando só os itens que o botão gera. */
  canGenerate: boolean;
  /** Nada pendente. */
  ready: boolean;
  missingCount: number;
  lastGeneratedAt: string | null;
};

async function currentConsultantId(): Promise<string | null> {
  const { data } = await supabase.auth.getUser();
  return data.user?.id ?? null;
}

export async function loadConsultantIdentityStatus(
  consultantIdInput?: string,
): Promise<IdentityStatus | null> {
  const consultantId = String(consultantIdInput || (await currentConsultantId()) || "").trim();
  if (!consultantId) return null;

  const [consRes, waRes, mediaRes, clipsRes] = await Promise.all([
    supabase
      .from("consultants")
      .select("id, name, display_name, assistant_name, gender, phone, identity_media_bootstrapped_at")
      .eq("id", consultantId)
      .maybeSingle(),
    supabase
      .from("whatsapp_instances")
      .select("connected_phone, instance_name")
      .eq("consultant_id", consultantId)
      .limit(5),
    (supabase as any)
      .from("ai_media_library")
      .select("slot_key, active")
      .eq("consultant_id", consultantId)
      .eq("active", true)
      .like("slot_key", "a2_audio_activate_name__body_%"),
    (supabase as any)
      .from("voice_audio_clips")
      .select("id, name, is_call_body")
      .eq("consultant_id", consultantId)
      .eq("is_call_body", true)
      .limit(500),
  ]);

  const cons = (consRes.data || null) as
    | {
        id: string;
        name: string | null;
        display_name: string | null;
        assistant_name: string | null;
        gender: string | null;
        phone: string | null;
        identity_media_bootstrapped_at: string | null;
      }
    | null;
  if (!cons) return null;

  const nomeOk = String(cons.name || "").trim().length >= 3;
  const iaName = String(cons.assistant_name || "").trim();
  const iaOk = iaName.length >= 2;
  const generoOk = ["consultor", "consultora"].includes(String(cons.gender || "").trim());
  const telOk = validateBrazilPhone(String(cons.phone || "")).valid;

  const waRows = Array.isArray(waRes.data) ? waRes.data : [];
  const waOk = waRows.some((r: any) => {
    const p = String(r?.connected_phone || "").replace(/\D/g, "");
    const n = String(r?.instance_name || "").toLowerCase();
    return p.length >= 10 || n.startsWith("whapi");
  });

  const a2Slots = new Set(
    ((mediaRes.data || []) as Array<{ slot_key: string }>).map((m) => m.slot_key),
  );
  const a2Total = 2;
  const a2Done =
    (a2Slots.has("a2_audio_activate_name__body_masculino") ? 1 : 0) +
    (a2Slots.has("a2_audio_activate_name__body_feminino") ? 1 : 0);

  const clips = (clipsRes.data || []) as Array<{ id: string; name: string | null }>;
  const identityClips = clips.filter((c) => /\[identidade\]/i.test(String(c.name || "")));
  const stagesCovered = IDENTITY_CALL_STAGES.filter((stage) =>
    identityClips.some((c) => String(c.name || "").toUpperCase().includes(stage)),
  ).length;
  const callsTotal = IDENTITY_CALL_STAGES.length;

  const consultorLabel = String(cons.name || cons.display_name || "").trim();

  const steps: IdentityStep[] = [
    {
      id: "nome",
      title: "Seu nome completo",
      why: "É o nome que o cliente ouve e lê nas mensagens.",
      how: "Aba Dados → campo Nome. Escreva seu nome real (ex.: Rafael Silva) e salve.",
      done: nomeOk,
      prerequisite: true,
      autoGenerated: false,
    },
    {
      id: "ia",
      title: "Nome da sua IA",
      why: "A assistente se apresenta com esse nome em todas as ligações.",
      how: 'Aba Dados → campo "Nome da assistente". Escolha um nome só seu (ex.: Ana, Bia). Não pode repetir nome já usado por outro consultor.',
      done: iaOk,
      prerequisite: true,
      autoGenerated: false,
    },
    {
      id: "genero",
      title: "Consultor ou consultora",
      why: 'Define se a frase sai "do Rafael" ou "da Sirlene".',
      how: "Aba Dados → selecione Consultor ou Consultora e salve.",
      done: generoOk,
      prerequisite: false,
      autoGenerated: false,
    },
    {
      id: "telefone",
      title: "Seu WhatsApp de contato",
      why: "É o número que entra no link wa.me enviado por SMS e nas ligações.",
      how: "Aba Dados → Telefone com DDD (ex.: 11 99999-9999) e salve.",
      done: telOk,
      prerequisite: true,
      autoGenerated: false,
    },
    {
      id: "whatsapp",
      title: "WhatsApp conectado",
      why: "Sem chip conectado o sistema não gera sua mídia nem dispara mensagens.",
      how: "Aba WhatsApp → Conectar → leia o QR Code com o celular.",
      done: waOk,
      prerequisite: true,
      autoGenerated: false,
    },
    {
      id: "a2",
      title: "Áudios de boas-vindas (com sua IA)",
      why: "Primeira mensagem de voz que o lead recebe no WhatsApp.",
      how: 'Clique em "Gerar minha identidade" — o sistema cria os 2 áudios (para homem e para mulher) falando seu nome.',
      done: a2Done >= a2Total,
      prerequisite: false,
      autoGenerated: true,
      progressLabel: `${a2Done} de ${a2Total} prontos`,
    },
    {
      id: "ligacoes",
      title: "Áudios das ligações (todas as etapas)",
      why: "Sem eles a ligação não sai — o sistema nunca usa áudio de outro consultor.",
      how: 'Clique em "Gerar minha identidade" — cria os áudios das 11 etapas de ligação com o seu nome.',
      done: stagesCovered >= callsTotal,
      prerequisite: false,
      autoGenerated: true,
      progressLabel: `${stagesCovered} de ${callsTotal} prontos`,
    },
  ];

  const prereqOk = steps.filter((s) => s.prerequisite).every((s) => s.done);
  const missingCount = steps.filter((s) => !s.done).length;

  return {
    consultantId,
    consultorLabel,
    assistantName: iaName,
    steps,
    canGenerate: prereqOk,
    ready: missingCount === 0,
    missingCount,
    lastGeneratedAt: cons.identity_media_bootstrapped_at,
  };
}
