/**
 * Banco Meta: headline + description + primary + CTWA.
 * PT-BR natural. Sem cidade na CTWA. Sem jargão de plano/assinatura.
 */

export const AD_HEADLINES: readonly string[] = [
  `Pague menos na conta de luz`,
  `Sua conta de luz pode baixar`,
  `Economize na conta de luz`,
  `Conta de luz mais barata`,
  `Quer pagar menos na luz?`,
  `Menos na fatura de luz`,
  `Conta alta? Tem jeito`,
  `Economize sem instalar placa`,
  `Pague menos todo mês`,
  `Sua fatura pode ficar menor`,
  `Luz mais barata no Zap`,
  `Reduza o valor da conta`,
  `Desconto na conta de luz`,
  `Conta de luz sem aperto`,
  `Simule sua economia`,
  `Pague só o justo na luz`,
  `Economia real na conta`,
  `Sua luz pode custar menos`,
  `Baixe o valor da fatura`,
  `Conta de luz sob controle`,
  `Tem como pagar menos`,
  `Economize na sua fatura`,
  `Luz barata, sem placa`,
  `Menos gasto com a luz`,
  `Veja se a conta baixa`,
  `Pague menos na CEMIG`,
  `Fatura menor é possível`,
  `Economia sem obra`,
  `Quer conta mais leve?`,
  `Desconto que aparece`,
  `Sua conta pode aliviar`,
  `Pague menos de verdade`,
  `Economize agora no Zap`,
  `Conta de luz com alívio`,
  `Tire a dúvida no Zap`,
  `Luz justa pro bolso`,
  `Menos R$ na conta`,
  `Economia fácil na luz`,
  `Sua fatura agradece`,
  `Pague menos sem placa`,
  `Conta alta tem saída`,
  `Simule no WhatsApp`,
  `Economize sem dor`,
  `Fatura mais leve`,
  `Quer economizar na luz?`,
  `Desconto na sua fatura`,
  `Luz sem pesar no bolso`,
  `Pague menos já`,
  `Conta menor todo mês`,
  `Economia na ponta`,
  `Sua luz mais barata`,
  `Veja quanto economiza`,
  `Sem placa, com economia`,
  `Dá pra baixar a conta`,
  `Pague o justo pela luz`,
  `Economia que faz sentido`,
  `Luz barata de verdade`,
  `Menos aperto na conta`,
  `Quer pagar menos?`,
  `Economize na CEMIG`,
  `Fatura sob controle`,
  `Desconto claro na conta`,
  `Sua economia começa aqui`,
  `Pague menos na luz hoje`,
  `Conta leve, sem painel`,
  `Economia sem enrolação`,
  `Luz que cabe no bolso`,
  `Baixe o peso da conta`,
  `Tem jeito de pagar menos`,
  `Economize na luz agora`,
  `Sua conta pode cair`,
  `Pague menos sem obra`,
  `Desconto na sua luz`,
  `Conta de luz mais leve`,
  `Quer ver a economia?`,
  `Economia na sua casa`,
  `Luz justa pra família`,
  `Menos gasto fixo`,
  `Pague menos, simples`,
  `Fatura que não aperta`,
  `Economize sem surpresa`,
  `Sua luz no controle`,
  `Conta alta? Responde`,
  `Pague menos na energia`,
  `Economia no WhatsApp`,
  `Luz barata pra você`,
  `Quer conta menor?`,
  `Desconto na fatura`,
  `Economize de verdade`,
  `Sua fatura pode cair`,
  `Pague menos todo dia`,
  `Conta de luz com jeito`,
  `Economia sem mistério`,
  `Luz mais leve agora`,
  `Veja se vale pra você`,
  `Pague menos na conta`,
  `Economize sem instalar`,
  `Sua conta mais barata`,
  `Luz barata no Zap`,
  `Comece pelo WhatsApp`,
];

/** Descrição curta sob o título (Meta Description). */
export const AD_DESCRIPTIONS: readonly string[] = [
  `Sem instalar placa`,
  `Simule no WhatsApp`,
  `Na sua fatura atual`,
  `Economia de verdade`,
  `Sem obra no telhado`,
  `Resposta no Zap`,
  `Pague só o justo`,
  `Conta pode baixar`,
  `Sem surpresa`,
  `Fácil e direto`,
  `Veja se cabe pra você`,
  `Desconto na fatura`,
  `Sem painel solar`,
  `Tire a dúvida agora`,
  `Economia possível`,
  `No WhatsApp`,
  `Clareza na conta`,
  `Sem enrolação`,
  `Rápido no Zap`,
  `Menos na conta`,
  `Fatura mais leve`,
  `Sem compromisso`,
  `Entenda em 1 minuto`,
  `Economia na luz`,
  `Pode valer pra você`,
  `Sem instalação`,
  `Conversa no Zap`,
  `Conta mais barata`,
  `Simples e claro`,
  `Alívio na fatura`,
  `Sem comprar placa`,
  `Veja a economia`,
  `Direto ao ponto`,
  `Na sua conta CEMIG`,
  `Economize de verdade`,
  `Só uma conversa`,
  `Sem pressão`,
  `Pague menos luz`,
  `Fatura sob controle`,
  `Comece no Zap`,
  `Sem mistério`,
  `Economia clara`,
  `Na ponta do lápis`,
  `Sem letra miúda`,
  `Ajuda no WhatsApp`,
  `Conta sem aperto`,
  `Desconto real`,
  `Fácil de entender`,
  `Sem obra nenhuma`,
  `Resposta objetiva`,
  `Sua luz mais barata`,
  `Explicação simples`,
  `Só o necessário`,
  `Baixe a fatura`,
  `Tem jeito de baixar`,
  `Converse conosco`,
  `Sem comprar nada`,
  `Economia no bolso`,
  `Conta mais leve`,
  `Simule no Zap`,
  `Sem dor de cabeça`,
  `Pague menos já`,
  `Fatura menor`,
  `Sem placa solar`,
  `Entenda no Zap`,
  `Economia fácil`,
  `Na sua casa`,
  `Desconto possível`,
  `Sem complicar`,
  `Luz mais barata`,
  `Tire a prova`,
  `Conta com alívio`,
  `Sem instalar nada`,
  `Resultado na fatura`,
  `Pergunte no Zap`,
  `Economia honesta`,
  `Sem enrolar`,
  `Pague o justo`,
  `Fatura aliviada`,
  `Comece agora`,
  `Sem surpresas`,
  `Economia prática`,
  `Na conta atual`,
  `Desconto na luz`,
  `Sem painel`,
  `Rápido e claro`,
  `Sua economia`,
  `Conversa franca`,
  `Sem obra`,
  `Menos gasto`,
  `Alívio na conta`,
  `Simule agora`,
  `Sem pressão alguma`,
  `Economia real`,
  `No seu bolso`,
  `Ajuda de verdade`,
  `Sem placa`,
  `Conta controlada`,
  `Luz no controle`,
  `WhatsApp agora`,
];

export const AD_PRIMARIES: readonly string[] = [
  `Quer saber se sua conta de luz pode baixar? Simule no WhatsApp.`,
  `Dá pra pagar menos na luz sem instalar placa. Chama no Zap e a gente explica.`,
  `Sua fatura pode ficar mais leve. Descubra no WhatsApp se cabe no seu caso.`,
  `Sem obra e sem painel: veja se dá pra economizar na conta de luz.`,
  `Conta alta todo mês? Veja no Zap se você consegue pagar menos.`,
  `Em um minuto no WhatsApp você simula quanto pode economizar.`,
  `O desconto aparece na fatura. Converse no Zap e confira.`,
  `Não precisa instalar nada. Só entender se vale pra você.`,
  `Muita gente em Minas já paga menos. Quer ver se você também consegue?`,
  `Pergunte no WhatsApp se a sua conta de luz pode cair.`,
  `Economia real na luz, sem surpresa. Tire a dúvida no Zap.`,
  `Se a conta apertou, tem caminho. Simule agora no WhatsApp.`,
  `Desconto na fatura sem placa no telhado. Fale conosco no Zap.`,
  `A gente explica no WhatsApp e você decide com calma.`,
  `Pagar menos luz não precisa de obra. Veja no WhatsApp.`,
  `Sua conta pode ficar menor. Descubra em uma conversa no Zap.`,
  `Simule sua economia na CEMIG pelo WhatsApp. É rápido.`,
  `Sem instalação. Com chance de pagar menos. Chama no WhatsApp.`,
  `Quer clareza sobre a conta? A gente responde no Zap.`,
  `Menos na fatura todo mês: veja se faz sentido pra você.`,
  `Conta de luz subindo? Pergunte no Zap se dá pra baixar.`,
  `Economia na luz sem comprar equipamento. Fale conosco.`,
  `A gente mostra o cálculo no WhatsApp, sem compromisso.`,
  `Faça as contas com a gente. Simule sua conta no Zap.`,
  `Quer pagar menos na CEMIG? Entenda em dois minutos no Zap.`,
  `Não é mágica: é desconto na fatura. Quer ver como funciona?`,
  `Se o seu perfil encaixa, a conta fica mais leve. Chama no Zap.`,
  `Tire a dúvida agora: sua luz pode ficar mais barata.`,
  `Sem enrolação. Explicamos no WhatsApp se vale a pena.`,
  `Quer ver se a fatura pode ficar menor? Simule no Zap.`,
  `Você continua com a mesma luz e pode pagar menos.`,
  `Economia na conta de luz, sem instalar placa. Saiba mais no Zap.`,
  `Conta pesada? Veja uma opção sem instalar placa.`,
  `Um toque no Zap e você já vê se a economia faz sentido.`,
  `O desconto aparece na fatura. Converse e confira no Zap.`,
  `Não precisa decidir agora: só entender no WhatsApp.`,
  `Conta alta dói. Tem jeito sem obra. Chama no Zap.`,
  `A gente fala claro: quanto economiza e como funciona.`,
  `Sua família merece fatura mais leve. Simule no Zap.`,
  `Economia na luz sem painel. Pergunte no WhatsApp.`,
  `Veja se o desconto cabe na sua conta da CEMIG.`,
  `Rápido e direto no Zap: simule sua economia.`,
  `Menos gasto fixo com luz. Descubra se é pra você.`,
  `Sem placa solar. Com possibilidade de pagar menos.`,
  `Explicação simples no WhatsApp. Sem pressão.`,
  `Sua fatura pode surpreender pra menos. Chama no Zap.`,
  `Quer ver a economia na conta? Tire a dúvida no Zap.`,
  `Se a luz pesa no orçamento, converse conosco no Zap.`,
  `Explicação clara, sem letra miúda. Pergunte no Zap.`,
  `Um zap e você já sabe se vale. Simples assim.`,
  `Pagar o justo pela luz: veja a opção no WhatsApp.`,
  `Dá pra pagar menos na luz se o seu caso encaixar. Confira.`,
  `Não instala. Não complica. Pode economizar.`,
  `Mesma fatura CEMIG, com chance de pagar menos. Saiba mais.`,
  `Conta sob controle começa com uma pergunta no Zap.`,
  `A gente mostra números, não promessa vazia.`,
  `Quer pagar menos todo mês? Simule agora no Zap.`,
  `Luz barata de verdade: entenda no WhatsApp.`,
  `Sem obra no telhado. Com conversa franca no Zap.`,
  `Pode ter desconto na conta. Descubra em um minuto.`,
  `Fatura que não aperta: veja se é possível no Zap.`,
  `Economia sem dor de cabeça. Chama no WhatsApp.`,
  `A mesma energia, com conta potencialmente menor.`,
  `Tire dois minutos e simule sua economia no Zap.`,
  `Quer desconto na conta de luz? Pergunte no Zap.`,
  `A gente explica no Zap se a sua conta pode cair.`,
  `Sem surpresa: falamos o que cabe no seu caso.`,
  `Conta alta? Responde e a gente calcula no Zap.`,
  `Minas, CEMIG e economia: combine no WhatsApp.`,
  `Menos reais na conta é o objetivo. Simule no Zap.`,
  `Você pergunta, a gente responde claro no Zap.`,
  `Economia possível sem instalar equipamento.`,
  `Veja se economiza antes de decidir. É no Zap.`,
  `Fatura menor, conversa simples. Comece no WhatsApp.`,
  `Não é golpe nem milagre: é desconto na conta.`,
  `Se fizer sentido, você segue. Se não, tudo bem.`,
  `Simule, compare e decida com calma no WhatsApp.`,
  `Sua luz pode ficar mais leve. Confira no Zap.`,
  `Desconto na conta quando o caso encaixa. Chama no Zap.`,
  `Economia na conta de luz, explicada fácil no Zap.`,
  `Um clique, um Zap e uma simulação objetiva.`,
  `Pague menos se couber. A gente te mostra no Zap.`,
  `Conta de luz não precisa apertar tanto. Veja no Zap.`,
  `Sem painel. Com pergunta sincera no WhatsApp.`,
  `Economia na fatura CEMIG: tire a dúvida hoje no Zap.`,
  `A gente não empurra: a gente explica no Zap.`,
  `Quer clareza na conta? Comece com um oi no Zap.`,
  `Menos na conta de luz, sem instalação. Chama no Zap.`,
  `Sua economia começa com uma mensagem no WhatsApp.`,
  `Simule agora e veja se a conta pode baixar.`,
  `Luz justa pro bolso. Converse conosco no Zap.`,
  `A economia aparece na fatura. Entenda como no Zap.`,
  `Sem enrolação e sem placa. Só economia possível.`,
  `CEMIG na fatura, clareza no Zap. Vamos conversar.`,
  `Se a conta subiu, tem caminho. Pergunte no Zap.`,
  `Menos gasto com luz, mesmo conforto em casa.`,
  `Fale no WhatsApp e receba a simulação.`,
  `Pagar menos luz pode ser mais simples do que parece.`,
  `Veja se você se encaixa e quanto economiza.`,
  `Comece pelo Zap: é rápido e sem compromisso.`,
];

/** CTWA genéricas — aprovadas, sem cidade. */
export const CTWA_ANCHOR: readonly string[] = [
  `Oi! Quero saber como consigo pagar menos na conta de luz.`,
  `Oi! Vi que dá pra pagar menos na conta de luz. Quero saber como funciona.`,
  `Oi! Quero pagar menos na conta de luz. Pode me explicar?`,
  `Oi! Minha conta de luz está alta. Tem como pagar menos?`,
  `Oi! Vi o anúncio e quero saber se dá pra economizar na conta de luz.`,
  `Oi! Quero entender como reduzir o valor da conta de luz.`,
  `Oi! Tenho interesse em pagar menos na conta de luz.`,
  `Oi! Conta de luz tá pesada. Quero ver se consigo economizar.`,
  `Oi! Quero saber se minha conta de luz pode ficar mais barata.`,
  `Oi! Vi sobre pagar menos na luz. Quero mais informação.`,
  `Oi! Quero simular quanto posso economizar na conta de luz.`,
  `Oi! Dá pra baixar o valor da conta de luz? Quero saber.`,
  `Oi! Quero conversar sobre economizar na conta de luz.`,
  `Oi! Vi o anúncio de conta de luz mais barata. Pode me atender?`,
  `Oi! Quero saber como funciona pra pagar menos na luz.`,
  `Oi! Minha fatura de luz subiu. Tem como reduzir?`,
  `Oi! Quero pagar menos todo mês na conta de luz.`,
  `Oi! Vi que tem como economizar na luz sem instalar placa. É isso?`,
  `Oi! Quero entender se consigo desconto na conta de luz.`,
  `Oi! Conta de luz alta. Quero ver se tem jeito de pagar menos.`,
  `Oi! Quero saber mais sobre pagar menos na conta de luz.`,
  `Oi! Cheguei pelo anúncio. Quero economizar na conta de luz.`,
  `Oi! Quero ver se vale a pena pra mim pagar menos na luz.`,
  `Oi! Tem como a conta de luz ficar mais barata? Quero saber.`,
  `Oi! Quero uma explicação de como pagar menos na conta de luz.`,
  `Oi! Vi o anúncio no Facebook. Quero pagar menos na luz.`,
  `Oi! Quero reduzir o que pago na conta de luz.`,
  `Oi! Conta de luz tá cara. Querem me ajudar a pagar menos?`,
  `Oi! Quero saber se dá pra economizar na minha conta de luz.`,
  `Oi! Interesse em pagar menos na conta de luz. Me explica?`,
  `Oi! Quero tirar uma dúvida sobre economizar na conta de luz.`,
  `Oi! Vi que a conta pode baixar. Como funciona?`,
  `Oi! Quero informação sobre pagar menos na conta de luz.`,
  `Oi! Dá pra pagar menos na luz sem colocar placa no telhado?`,
  `Oi! Quero saber o passo a passo pra economizar na conta de luz.`,
  `Oi! Minha conta de luz aperta o orçamento. Tem como baixar?`,
  `Oi! Quero conversar sobre conta de luz mais barata.`,
  `Oi! Vi o anúncio e fiquei interessado em pagar menos na luz.`,
  `Oi! Quero ver quanto posso economizar na conta de luz.`,
  `Oi! Quero saber se consigo pagar menos na conta de luz.`,
  `Oi! Quero clareza sobre como economizar na conta de luz.`,
  `Oi! Cheguei aqui pelo anúncio de economia na luz.`,
  `Oi! Quero pagar menos na fatura de luz. Como faço?`,
  `Oi! Tem jeito de a conta de luz ficar menor? Quero saber.`,
  `Oi! Quero entender melhor essa economia na conta de luz.`,
  `Oi! Vi sobre conta de luz mais barata. Quero detalhes.`,
  `Oi! Quero saber se isso funciona pra pagar menos na luz.`,
  `Oi! Conta alta de luz. Quero ver se consigo economizar.`,
  `Oi! Quero uma simulação de economia na conta de luz.`,
  `Oi! Posso pagar menos na conta de luz? Me explica como.`,
  `Oi! Quero saber como baixar o valor que pago de luz.`,
  `Oi! Vi o anúncio. Quero economizar na minha conta de luz.`,
  `Oi! Quero informação séria sobre pagar menos na luz.`,
  `Oi! A conta de luz tá pesando. Quero pagar menos.`,
  `Oi! Quero ver se minha conta de luz pode diminuir.`,
  `Oi! Tenho conta de luz cara. Dá pra pagar menos?`,
  `Oi! Quero saber dessa forma de economizar na conta de luz.`,
  `Oi! Vi que dá pra reduzir a conta de luz. Quero entender.`,
  `Oi! Quero começar a conversa sobre pagar menos na luz.`,
  `Oi! A conta de luz do mês tá alta. Quero economizar.`,
  `Oi! Quero saber se consigo pagar menos na luz daqui de casa.`,
  `Oi! Cheguei pelo anúncio e quero pagar menos na conta de luz.`,
  `Oi! Quero tirar dúvida. Dá pra economizar na conta de luz?`,
  `Oi! Minha luz tá cara. Quero ver a possibilidade de pagar menos.`,
  `Oi! Quero mais detalhes de como pagar menos na conta de luz.`,
  `Oi! Vi o Zap do anúncio. Quero economizar na conta de luz.`,
  `Oi! Quero saber se a economia na conta de luz é pra mim.`,
  `Oi! Conta de luz subindo. Tem como pagar menos?`,
  `Oi! Quero uma resposta simples. Como pagar menos na luz?`,
  `Oi! Interesse real em economizar na conta de luz.`,
  `Oi! Quero falar sobre reduzir a conta de luz.`,
  `Oi! Vi o anúncio de pagar menos na luz. Pode me ajudar?`,
  `Oi! Quero entender na prática como a conta de luz fica menor.`,
  `Oi! Conta de luz tá difícil. Quero saber se dá pra baixar.`,
  `Oi! Quero saber como funciona pra economizar na luz.`,
  `Oi! Cheguei agora. Quero pagar menos na conta de luz.`,
  `Oi! Quero ver se tem economia na minha conta de luz.`,
  `Oi! Minha fatura de energia tá alta. Quero pagar menos.`,
  `Oi! Quero conversar pra saber se consigo economizar na luz.`,
  `Oi! Vi sobre economizar na conta de luz. Quero saber mais.`,
  `Oi! Quero pagar menos na luz. Como começa?`,
  `Oi! Conta de luz cara todo mês. Quero uma alternativa.`,
  `Oi! Quero saber se consigo reduzir o que pago de luz.`,
  `Oi! Vi o anúncio de conta mais barata. Quero economizar na luz.`,
  `Oi! Quero explicação clara de como pagar menos na conta de luz.`,
  `Oi! Tô com a conta de luz alta. Dá pra pagar menos?`,
  `Oi! Quero simular a economia na minha conta de luz.`,
  `Oi! Vi que não precisa instalar placa. Quero pagar menos na luz.`,
  `Oi! Quero saber se minha conta de luz encaixa pra economizar.`,
  `Oi! Quero conta de luz mais barata. Pode me orientar?`,
  `Oi! Quero baixar o valor da minha conta de luz.`,
  `Oi! Conta de luz apertando. Quero ver se economizo.`,
  `Oi! Quero informação sobre economia na conta de luz.`,
  `Oi! Cheguei pelo Facebook. Quero pagar menos na luz.`,
  `Oi! Quero saber o caminho pra pagar menos na conta de luz.`,
  `Oi! Minha luz tá cara. Quero conversar sobre economizar.`,
  `Oi! Quero ver na prática se a conta de luz pode baixar.`,
  `Oi! Vi o anúncio e quero pagar menos na conta de luz.`,
  `Oi! Quero uma ajuda pra economizar na conta de luz.`,
  `Oi! Quero pagar menos na conta de luz. Podem me explicar?`,
];

export const CTWA_EXPLORER: readonly string[] = CTWA_ANCHOR;

export type AdCopyPick = {
  headline: string;
  description: string;
  primary_text: string;
  initial_message: string;
  headline_idx: number;
  description_idx: number;
  primary_idx: number;
  ctwa_idx: number;
  fingerprint: string;
};

function norm(s: string): string {
  return s.toLowerCase().normalize("NFD").replace(/[̀-ͯ]/g, "").replace(/\s+/g, " ").trim();
}

function hashSlug(slug: string): number {
  let h = 2166136261;
  const key = (slug || "x").toLowerCase();
  for (let i = 0; i < key.length; i++) {
    h ^= key.charCodeAt(i);
    h = Math.imul(h, 16777619);
  }
  return h >>> 0;
}

function idxFor(slug: string, salt: string, n: number, attempt = 0): number {
  const base = hashSlug(`${slug}::${salt}`);
  return (base + attempt * 17) % n;
}

export function fingerprintCopy(h: string, d: string, p: string, c: string): string {
  return `${norm(h)}||${norm(d)}||${norm(p)}||${norm(c)}`;
}

export function pickAdCopyForCity(opts: {
  slug: string;
  cityName: string;
  isAnchor?: boolean;
  usedInitialMessages?: string[];
  usedFingerprints?: string[];
}): AdCopyPick {
  const n = AD_HEADLINES.length;
  const slug = opts.slug || opts.cityName || "mg";
  const usedMsg = new Set((opts.usedInitialMessages || []).map(norm));
  const usedFp = new Set(opts.usedFingerprints || []);

  for (let attempt = 0; attempt < n; attempt++) {
    const hi = idxFor(slug, "headline", n, attempt);
    const di = idxFor(slug, "description", n, attempt);
    const pi = idxFor(slug, "primary", n, attempt);
    const ci = idxFor(slug, "ctwa", n, attempt);
    const headline = AD_HEADLINES[hi].slice(0, 40);
    const description = AD_DESCRIPTIONS[di].slice(0, 25);
    const primary_text = AD_PRIMARIES[pi];
    const initial_message = CTWA_ANCHOR[ci].slice(0, 160);
    if (usedMsg.has(norm(initial_message))) continue;
    const fp = fingerprintCopy(headline, description, primary_text, initial_message);
    if (usedFp.has(fp)) continue;
    return {
      headline,
      description,
      primary_text,
      initial_message,
      headline_idx: hi,
      description_idx: di,
      primary_idx: pi,
      ctwa_idx: ci,
      fingerprint: fp,
    };
  }

  const hi = idxFor(slug, "headline", n, 0);
  const di = idxFor(slug, "description", n, 0);
  const pi = idxFor(slug, "primary", n, 0);
  const ci = idxFor(slug, "ctwa", n, 0);
  const headline = AD_HEADLINES[hi].slice(0, 40);
  const description = AD_DESCRIPTIONS[di].slice(0, 25);
  const primary_text = AD_PRIMARIES[pi];
  const initial_message = CTWA_ANCHOR[ci].slice(0, 160);
  return {
    headline,
    description,
    primary_text,
    initial_message,
    headline_idx: hi,
    description_idx: di,
    primary_idx: pi,
    ctwa_idx: ci,
    fingerprint: fingerprintCopy(headline, description, primary_text, initial_message),
  };
}

