import { useCallback, useEffect, useState } from "react";
import {
  BadgeCheck,
  CheckCircle2,
  Circle,
  Loader2,
  Mic,
  RefreshCw,
  Sparkles,
  Wand2,
} from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { useToast } from "@/components/ui/use-toast";
import { cn } from "@/lib/utils";
import {
  loadConsultantIdentityStatus,
  type IdentityStatus,
  type IdentityStep,
} from "@/lib/consultantIdentityReadiness";
import { invokeConsultantIdentityBootstrap } from "@/lib/consultantIdentityBootstrap";

type Props = {
  consultantId?: string;
  className?: string;
  /** Esconde o card quando estiver tudo pronto (padrão: mostra resumo verde). */
  hideWhenReady?: boolean;
};

function openDados() {
  window.dispatchEvent(new CustomEvent("igreen-admin-open-settings"));
}

function openWhatsApp() {
  window.dispatchEvent(new CustomEvent("igreen-admin-nav", { detail: { tab: "whatsapp" } }));
}

function StepRow({ step }: { step: IdentityStep }) {
  return (
    <li
      className={cn(
        "flex items-start gap-2.5 rounded-lg border p-2.5",
        step.done ? "border-emerald-500/30 bg-emerald-500/5" : "border-amber-500/40 bg-amber-500/5",
      )}
    >
      {step.done ? (
        <CheckCircle2 className="mt-0.5 h-4 w-4 shrink-0 text-emerald-600" />
      ) : (
        <Circle className="mt-0.5 h-4 w-4 shrink-0 text-amber-600" />
      )}
      <div className="min-w-0 flex-1">
        <div className="flex flex-wrap items-center gap-x-2 gap-y-1">
          <span className="text-sm font-semibold">{step.title}</span>
          {step.progressLabel && (
            <span
              className={cn(
                "rounded-full px-1.5 py-0.5 text-[10px] font-semibold",
                step.done ? "bg-emerald-500/15 text-emerald-700" : "bg-amber-500/20 text-amber-800",
              )}
            >
              {step.progressLabel}
            </span>
          )}
        </div>
        <p className="mt-0.5 text-[11px] text-muted-foreground">{step.why}</p>
        {!step.done && (
          <p className="mt-1 text-[11px] font-medium text-foreground/90">Como resolver: {step.how}</p>
        )}
        {!step.done && !step.autoGenerated && (
          <Button
            size="sm"
            variant="outline"
            className="mt-1.5 h-7 text-[11px]"
            onClick={step.id === "whatsapp" ? openWhatsApp : openDados}
          >
            {step.id === "whatsapp" ? "Abrir WhatsApp" : "Abrir meus dados"}
          </Button>
        )}
      </div>
    </li>
  );
}

/**
 * Passo a passo (linguagem de leigo) para o consultor deixar TUDO com o
 * nome dele e a IA dele: dados → WhatsApp → gerar áudios próprios.
 */
export function ConsultantIdentityWizard({ consultantId, className, hideWhenReady }: Props) {
  const { toast } = useToast();
  const [status, setStatus] = useState<IdentityStatus | null>(null);
  const [loading, setLoading] = useState(true);
  const [generating, setGenerating] = useState(false);

  const reload = useCallback(async () => {
    try {
      const next = await loadConsultantIdentityStatus(consultantId);
      setStatus(next);
    } catch {
      /* noop */
    } finally {
      setLoading(false);
    }
  }, [consultantId]);

  useEffect(() => {
    void reload();
  }, [reload]);

  async function generate() {
    if (!status) return;
    setGenerating(true);
    const res = await invokeConsultantIdentityBootstrap({
      consultantId: status.consultantId,
      force: true,
    });
    setGenerating(false);
    if (!res.ok) {
      toast({
        title: "Não deu para gerar agora",
        description:
          res.error === "ELEVENLABS_API_KEY_missing"
            ? "A voz da IA está indisponível no momento. Avise o suporte."
            : res.reason || res.error || "Tente novamente em alguns minutos.",
        variant: "destructive",
      });
      return;
    }
    if (res.skipped) {
      toast({
        title: "Nada a gerar",
        description:
          res.reason === "whatsapp_not_connected"
            ? "Conecte seu WhatsApp primeiro."
            : "Sua identidade já está atualizada.",
      });
    } else {
      toast({
        title: "Identidade gerada",
        description: "Seus áudios já falam o seu nome e o nome da sua IA.",
      });
    }
    await reload();
  }

  if (loading) {
    return (
      <div className={cn("flex items-center gap-2 p-3 text-xs text-muted-foreground", className)}>
        <Loader2 className="h-3.5 w-3.5 animate-spin" /> Conferindo sua identidade...
      </div>
    );
  }
  if (!status) return null;
  if (status.ready && hideWhenReady) return null;

  const total = status.steps.length;
  const done = total - status.missingCount;
  const pct = Math.round((done / total) * 100);

  return (
    <Card
      className={cn(
        "border-2",
        status.ready ? "border-emerald-500/40" : "border-amber-500/60",
        className,
      )}
    >
      <CardHeader className="pb-3">
        <div className="flex flex-wrap items-start justify-between gap-2">
          <div className="min-w-0">
            <CardTitle className="flex items-center gap-2 text-base">
              {status.ready ? (
                <BadgeCheck className="h-5 w-5 text-emerald-600" />
              ) : (
                <Sparkles className="h-5 w-5 text-amber-600" />
              )}
              Minha identidade ({done}/{total})
            </CardTitle>
            <CardDescription className="mt-1 text-xs">
              {status.ready
                ? `Tudo pronto: as mensagens e ligações saem com ${status.consultorLabel || "o seu nome"} e a IA ${status.assistantName}.`
                : "O cliente só pode ouvir o SEU nome e a SUA IA. Complete os itens abaixo — leva poucos minutos."}
            </CardDescription>
          </div>
          <div className="flex shrink-0 gap-2">
            <Button variant="ghost" size="sm" onClick={() => void reload()} disabled={generating}>
              <RefreshCw className="mr-1 h-3.5 w-3.5" /> Atualizar
            </Button>
            <Button size="sm" onClick={() => void generate()} disabled={generating || !status.canGenerate}>
              {generating ? (
                <Loader2 className="mr-1 h-3.5 w-3.5 animate-spin" />
              ) : (
                <Wand2 className="mr-1 h-3.5 w-3.5" />
              )}
              Gerar minha identidade
            </Button>
          </div>
        </div>
        <div className="mt-2 h-1.5 w-full overflow-hidden rounded-full bg-muted">
          <div
            className={cn("h-full rounded-full transition-all", status.ready ? "bg-emerald-500" : "bg-amber-500")}
            style={{ width: `${pct}%` }}
          />
        </div>
      </CardHeader>
      <CardContent className="pt-0">
        {!status.canGenerate && (
          <p className="mb-2 rounded-md bg-amber-500/10 px-2.5 py-1.5 text-[11px] font-medium text-amber-800">
            Antes de gerar os áudios: preencha seu nome, o nome da sua IA, seu telefone e conecte o WhatsApp.
          </p>
        )}
        <ul className="grid gap-2 sm:grid-cols-2">
          {status.steps.map((s) => (
            <StepRow key={s.id} step={s} />
          ))}
        </ul>
        <p className="mt-2 flex items-center gap-1.5 text-[11px] text-muted-foreground">
          <Mic className="h-3 w-3" />
          O sistema nunca usa o áudio de outro consultor. Se faltar o seu, a ligação não sai — por segurança.
        </p>
      </CardContent>
    </Card>
  );
}

export default ConsultantIdentityWizard;
