import type { TourArticle, TourStep } from "@/features/onboarding/types";

export type HelpArticle = TourArticle & {
  summary: string;
  href: string;
  keywords: string[];
  steps: string[];
  featured?: boolean;
};

export const HELP_CATEGORIES = [
  "Primeiros passos",
  "Clientes e CRM",
  "WhatsApp e IA",
  "Captação e anúncios",
  "Automações",
  "Produtos e vendas",
  "Financeiro",
  "Pós-venda",
  "Conta e suporte",
] as const;

const article = (
  id: string,
  category: (typeof HELP_CATEGORIES)[number],
  title: string,
  summary: string,
  href: string,
  keywords: string[],
  steps: string[],
  order_index: number,
  featured = false,
): HelpArticle => ({
  id: `guia-${id}`,
  category,
  title,
  summary,
  body: steps.map((step, index) => `${index + 1}. ${step}`).join("\n"),
  href,
  keywords,
  steps,
  order_index,
  featured,
  video_url: null,
  related_tour_step_id: null,
  is_active: true,
});

export const HELP_CATALOG: HelpArticle[] = [
  article(
    "inicio",
    "Primeiros passos",
    "Comece por aqui",
    "Configure o essencial em ordem: conta, WhatsApp, links e primeiros contatos.",
    "/admin?tab=dashboard",
    ["início", "configurar", "primeiro acesso", "painel", "passo a passo"],
    [
      "No canto inferior direito, toque no botão verde de ajuda (?) se quiser repetir esta orientação a qualquer momento.",
      "No menu esquerdo, clique em Painel e confira avisos e pendências do dia.",
      "Abra Configurações (ícone de engrenagem / menu da conta no topo) e confirme seu nome e ID iGreen.",
      "No menu, clique em WhatsApp. Se aparecer Conectar → ou Conectar WhatsApp, leia o QR Code com o celular.",
      "No menu, clique em Links → aba Meus Links → escolha um produto → clique em Copiar e teste o endereço no navegador.",
      "No menu, clique em Clientes interessados para ver quem já chegou. Abra um card pelo ícone de olho para ver a conversa.",
      "Se algo falhar, volte ao botão verde de ajuda e escolha Perguntar ao suporte com IA descrevendo a tela e o que tentou.",
    ],
    1,
    true,
  ),
  article(
    "painel",
    "Primeiros passos",
    "Entenda o Painel",
    "Use indicadores e atalhos do Painel para ir direto ao que precisa de atenção.",
    "/admin?tab=dashboard",
    ["dashboard", "indicadores", "resultado", "pendência", "atalho"],
    [
      "No menu esquerdo, clique em Painel.",
      "No topo, confira o período (ex.: últimos 30 dias) antes de comparar números.",
      "Leia os cards de indicadores: clique em um card ou pendência para ir à área correspondente (WhatsApp, CRM, Financeiro, etc.).",
      "Se houver alerta de WhatsApp desconectado, clique no aviso ou abra WhatsApp no menu e use Conectar WhatsApp.",
      "Use os atalhos da tela para abrir Captação, Conversão ou Anúncios sem procurar no menu.",
      "Em dúvida sobre um número, abra o suporte com IA e diga qual card do Painel você está olhando.",
    ],
    2,
  ),
  article(
    "clientes-interessados",
    "Clientes e CRM",
    "Atenda clientes interessados",
    "No funil Kanban: buscar, abrir o card, ver conversa e mover a etapa.",
    "/admin?tab=crm",
    ["lead", "kanban", "interessado", "funil", "crm", "card"],
    [
      "No menu esquerdo (grupo Visão Geral), clique em Clientes interessados.",
      "No campo Buscar cliente interessado..., digite nome ou telefone.",
      "Use o filtro Parou no passo para achar quem travou em uma etapa.",
      "No card desejado, clique no ícone de olho (Ver detalhes, linha do tempo e próxima mensagem).",
      "Leia a conversa e os dados capturados; se precisar falar na hora, abra o WhatsApp a partir do contato.",
      "Arraste o card entre colunas para atualizar a etapa, ou use o menu ⋮ → Editar.",
      "Para incluir alguém na mão: clique em Adicionar Cliente interessado → preencha → Salvar.",
      "Se a lista for longa, role até Carregar mais deals.",
    ],
    10,
    true,
  ),
  article(
    "clientes-ativos",
    "Clientes e CRM",
    "Acompanhe clientes ativos",
    "Clientes já no iGreen: situação, documentos, cadastro em análise e pós-venda.",
    "/admin?tab=crm-clientes",
    ["ativo", "validado", "cliente igreen", "sincronização", "análise"],
    [
      "No menu esquerdo, clique em Clientes ativos (não confunda com Clientes interessados).",
      "Aqui ficam quem já enviou cadastro / está em análise na iGreen, aprovado, reprovado ou em acompanhamento 30–120 dias.",
      "Digite nome, telefone ou situação no campo de busca no topo da tela.",
      "Clique no card ou na linha do cliente para abrir detalhes, documentos e histórico.",
      "Se os dados parecerem antigos, clique em sincronizar / atualizar quando o botão aparecer na ficha.",
      "Trate devolutivas e pendências; depois arraste o card na coluna correta do Kanban de pós-venda.",
    ],
    11,
  ),
  article(
    "base-clientes",
    "Clientes e CRM",
    "Consulte a base de clientes",
    "Lista completa para achar cadastro, documento e origem.",
    "/admin?tab=clientes",
    ["cadastro", "documento", "base", "pesquisar cliente", "lista"],
    [
      "No menu esquerdo, clique em Base de clientes.",
      "Digite nome, telefone ou documento na busca.",
      "Use os filtros da lista (situação / origem) para reduzir o resultado.",
      "Clique na linha do cliente para abrir o cadastro completo.",
      "Altere só os campos necessários e salve.",
      "Se precisar falar com a pessoa, copie o telefone ou abra o WhatsApp a partir do registro.",
    ],
    12,
  ),
  article(
    "conversao",
    "Clientes e CRM",
    "Recupere oportunidades",
    "Atender agora: quem precisa de você, quem esfriou e o que falar.",
    "/admin?tab=conversao",
    ["conversão", "reativar", "lead parado", "oportunidade", "quente", "frio", "atender"],
    [
      "No menu esquerdo, clique em Conversão.",
      "Na aba Atender, comece pelo balde Precisa de você (automação pausada).",
      "Se estiver vazio, veja Quente sem resposta — prontos pra fechar que sumiram.",
      "Clique em Atender, leia o resumo e envie a mensagem ou abra o chat.",
      "Use Toda a fila só quando quiser ver todo mundo ainda não cliente.",
      "Para vários de uma vez (fora de Precisa de você): Selecionar vários → Enviar mensagem.",
      "Frases, Resultados e Ajustes ficam nas outras abas.",
    ],
    13,
  ),
  article(
    "whatsapp-conectar",
    "WhatsApp e IA",
    "Conecte o WhatsApp",
    "Passo a passo do QR Code até o status conectado.",
    "/admin?tab=whatsapp",
    ["qr code", "conectar", "instância", "número", "desconectado", "whatsapp"],
    [
      "No menu esquerdo (Gestão Comercial), clique em WhatsApp.",
      "Se o topo mostrar Conectar → ou status desconectado, continue neste guia.",
      "No painel Conexão WhatsApp, clique no botão Conectar WhatsApp.",
      "Quando aparecer Escaneie / QR Code, no celular abra WhatsApp → Configurações → Dispositivos conectados → Conectar dispositivo e leia o QR.",
      "Se o QR expirar, clique em Gerar novo QR ou Atualizar agora e tente de novo.",
      "Espere o status mudar para conectado antes de testar envio de mensagem.",
      "Para trocar de chip: clique em Desconectar / trocar chip → confirme em Sim, desconectar → conecte o novo número.",
      "Se travar: use Resetar Conexão (com cuidado) e depois Conectar WhatsApp novamente.",
    ],
    20,
    true,
  ),
  article(
    "whatsapp-atendimento",
    "WhatsApp e IA",
    "Atenda pelo WhatsApp",
    "Abas Conversas e Atendente IA: responder manual e devolver à automação.",
    "/admin?tab=whatsapp",
    ["conversa", "mensagem", "responder", "pausar ia", "humano", "atendente"],
    [
      "No menu, clique em WhatsApp.",
      "Clique na sub-aba Conversas.",
      "Clique na conversa na lista à esquerda e leia o histórico.",
      "Digite a resposta no campo de mensagem e envie. Resposta manual pode pausar a automação daquela conversa.",
      "Clique na sub-aba Atendente IA e confira se a assistente está ativa para o atendimento.",
      "Quando quiser devolver à automação, clique na opção de reativar / retomar atendimento automático na conversa (quando aparecer).",
      "Outras sub-abas: Envio em Massa, Templates, Agendamentos e Histórico — só clique em Envio em Massa depois de revisar a mensagem.",
    ],
    21,
  ),
  article(
    "ia-conhecimento",
    "WhatsApp e IA",
    "Ensine a assistente de IA",
    "Cadastre respostas corretas na Base de conhecimento e teste antes de publicar.",
    "/admin/conhecimento",
    ["faq", "base da ia", "conhecimento", "resposta", "embeddings"],
    [
      "No navegador, abra a Base de conhecimento (atalho do menu de ajuda ou endereço /admin/conhecimento).",
      "Clique para criar uma nova seção (ou editar uma existente).",
      "Escreva um título claro (ex.: “Cobertura CEMIG”) e o texto completo da resposta que a assistente deve usar.",
      "Inclua palavras e frases que o cliente costuma digitar (sinônimos e gírias).",
      "Salve. Se a tela pedir para atualizar o índice da IA, confirme essa ação.",
      "Teste com uma pergunta real no simulador ou no WhatsApp antes de mudanças grandes.",
      "Evite informações inventadas (preço, prazo, política). Se não souber, não cadastre.",
    ],
    22,
    true,
  ),
  article(
    "fluxos",
    "WhatsApp e IA",
    "Configure o fluxo de atendimento",
    "Editor de fluxos: editar um passo, simular e só então ativar.",
    "/admin/fluxos",
    ["fluxo", "mensagem automática", "passo", "pergunta", "editor", "simulador"],
    [
      "Abra Fluxos de atendimento em /admin/fluxos (ferramenta avançada).",
      "Escolha o fluxo que deseja revisar na lista.",
      "Clique em um passo para editar a mensagem, pergunta ou caminho.",
      "Altere um passo por vez e confira as saídas (para onde o cliente vai em cada resposta).",
      "Salve as alterações.",
      "Use o simulador da tela para testar a conversa completa.",
      "Só ative / publique para clientes depois do teste. Em dúvida, pergunte ao suporte com IA antes de mudar o fluxo principal.",
    ],
    23,
  ),
  article(
    "audio-studio",
    "WhatsApp e IA",
    "Use o Estúdio de áudio",
    "Gere áudio com voz Sofia/Diego/Rafael, baixe e envie no WhatsApp.",
    "/admin?tab=audio-studio",
    ["áudio", "estúdio", "gerar", "sofia", "vinheta"],
    [
      "No menu (Recursos), clique em Estúdio de áudio.",
      "Escolha o tipo: Mutirão, Comércio ou Texto livre.",
      "Escolha a voz: Sofia, Diego ou Rafael.",
      "Clique em Gerar áudio (o botão mostra o tipo escolhido).",
      "Ouça a prévia. Se precisar, clique em Gerar novamente.",
      "Clique em Baixar áudio (com ou sem vinheta, conforme as opções da tela).",
      "Para usar no atendimento: abra WhatsApp → Conversas e envie o arquivo na conversa desejada.",
      "Opcional: Publicar para outros consultores se a tela oferecer e você quiser compartilhar o áudio.",
    ],
    24,
  ),
  article(
    "captacao",
    "Captação e anúncios",
    "Acompanhe a captação",
    "Filtre leads novos, selecione e inicie atendimento.",
    "/admin?tab=captacao",
    ["captação", "lead ads", "origem", "formulário", "em espera"],
    [
      "No menu (Gestão Comercial), clique em Captação.",
      "Escolha o período: 48h, 7d, 30d, 60d, 90d ou Todos.",
      "Alterne entre as abas Em atendimento e Em espera.",
      "Use Buscar nome ou telefone para achar um lead.",
      "Marque leads com Selecionar todos ou Só sem atendimento; use Limpar seleção para desmarcar.",
      "Clique em Iniciar atendimento nos selecionados quando for assumir a conversa.",
      "No card do lead, confira se é o titular ou conta de outro titular antes de seguir o cadastro.",
    ],
    30,
  ),
  article(
    "central-anuncios",
    "Captação e anúncios",
    "Use a Central de anúncios",
    "Dashboard, campanhas, performance e atalho para criar anúncio.",
    "/admin?tab=central-anuncios",
    ["central de anúncios", "campanhas", "performance", "dashboard ads"],
    [
      "No menu (Recursos), clique em Central de anúncios.",
      "Clique nas abas Dashboard, Modelos, Campanhas, Performance, Inteligência ou Comissões conforme o que quiser ver.",
      "Para criar: clique em Anunciar rápido ou Montar completo.",
      "Se aparecer Como anunciar no WhatsApp em 4 passos, clique em Abrir aba WhatsApp, Conectar Facebook e Abrir Meta Business Suite na ordem pedida.",
      "Clique em Atualizar números para atualizar métricas; use Ver último sync se algo parecer atrasado.",
      "Se ainda não vinculou a Meta, clique em Conectar minha conta (opcional) quando o botão aparecer.",
    ],
    31,
    true,
  ),
  article(
    "meta-ads",
    "Captação e anúncios",
    "Crie uma campanha Meta",
    "Wizard: região, criativo, texto, orçamento e publicar.",
    "/admin/meta-ads",
    ["facebook", "instagram", "campanha", "anúncio", "meta", "cpl", "publicar"],
    [
      "No menu clique em Central de anúncios → Anunciar rápido ou Montar completo.",
      "Confirme WhatsApp conectado; se pedir conta Meta, clique em Conectar minha conta.",
      "No assistente, avance pelas etapas: Região → Criativo → Texto & Mensagem → Orçamento → Revisar & Publicar.",
      "Em cada etapa, preencha os campos obrigatórios e clique em Continuar.",
      "Na revisão, confira público, criativo, mensagem e valor diário.",
      "Clique em Publicar campanha e aguarde a análise da Meta.",
      "Depois, no menu clique em Central de anúncios → Performance (ou Campanhas) para ver status e custo.",
    ],
    32,
    true,
  ),
  article(
    "campanha-reprovada",
    "Captação e anúncios",
    "Resolva uma campanha reprovada",
    "Leia o motivo da Meta, corrija e envie de novo.",
    "/admin/meta-ads",
    ["reprovada", "erro meta", "2446885", "whatsapp business", "política"],
    [
      "Abra Meta Ads ou Central de anúncios → Campanhas.",
      "Clique na campanha reprovada e leia o motivo completo na tela (não invente a causa).",
      "Confirme destino WhatsApp Business e se a conexão Meta/WhatsApp está válida.",
      "Corrija texto, imagem ou público conforme o motivo (ex.: política, destino, criativo).",
      "Salve e envie novamente para análise.",
      "Se o motivo continuar sem clareza, abra o suporte com IA e informe o nome exato da campanha e a mensagem de erro.",
    ],
    33,
  ),
  article(
    "links",
    "Captação e anúncios",
    "Compartilhe seus links",
    "Copiar link por produto, QR Code e panfleto.",
    "/admin?tab=links",
    ["link", "página", "landing page", "divulgar", "licença", "copiar", "qr"],
    [
      "No menu (Recursos), clique em Links.",
      "Abra a aba Meus Links (Resultados mostra desempenho).",
      "Toque no produto desejado (ex.: Conexão Green, Cadastro Rápido).",
      "Em cada rede (WhatsApp, Instagram, etc.), clique em Copiar.",
      "Cole o link em uma janela anônima do navegador e confira se abre sua página.",
      "Para QR: clique no ícone QR Code ao lado do link.",
      "Para impressão: no bloco Panfleto pra Gráfica, clique em Gerar.",
    ],
    34,
  ),
  article(
    "materiais",
    "Captação e anúncios",
    "Baixe materiais de divulgação",
    "Encontre e baixe imagens/vídeos prontos para anúncio ou cliente.",
    "/admin?tab=materiais",
    ["material", "baixar", "arquivo", "imagem", "vídeo", "divulgação"],
    [
      "No menu (Recursos), clique em Materiais.",
      "Escolha o produto ou pasta do material.",
      "Abra o arquivo desejado e use Baixar / download.",
      "Antes de anunciar, confira se o criativo está atualizado e permitido pela Meta.",
      "Guarde uma cópia e use no wizard de campanha (etapa Criativo) ou envie ao cliente pelo WhatsApp.",
    ],
    35,
  ),
  article(
    "agendamentos",
    "Automações",
    "Use a Central de automações",
    "Abas Mapa, Grupos, Agenda e Histórico + botão Guia.",
    "/admin?tab=agendamentos",
    ["automação", "agendamento", "mensagem programada", "central", "guia", "mapa"],
    [
      "No menu, clique em Agendamentos (título da tela: Central de Automações).",
      "Clique no botão Guia no topo para ver o que já funciona, o que pode ligar/desligar e a ordem segura.",
      "Use as abas: Mapa | Leads novos | Quem esfriou | Quem sumiu | Agenda | Carteira | Histórico.",
      "Na aba Agenda, escolha a sub-aba: Manual, Pós-venda, Reaquecimento, Campanhas ou Rodízios.",
      "Para agendar na mão: Agenda → Manual → Agendar nova → preencha → Agendar.",
      "Filtre Próximos envios por Todos, Motor A→B→C, Manual, Pós-venda, WA, Ligação ou Reaquecer.",
      "Em Ajustar todos os textos, revise frases antes de ligar envios em volume.",
      "Só ative interruptores depois de ler o Guia e conferir uma prévia no Histórico.",
    ],
    40,
    true,
  ),
  article(
    "cadencia",
    "Automações",
    "Configure o Motor de cadência",
    "Ligar envios automáticos e horários — preferir pela aba Quem esfriou.",
    "/admin/motor",
    ["cadência", "follow-up", "ligação", "sms", "sem resposta", "grupo b"],
    [
      "Caminho recomendado: no menu clique em Agendamentos → aba Quem esfriou. Atalho: /admin/motor.",
      "Leia o status Ligado / Desligado no topo da tela do motor.",
      "Para ligar: clique no switch → no diálogo Ligar o motor de cadência? clique em Confirmar e ligar.",
      "Revise estágios, intervalos e limites de WhatsApp, ligação e SMS nos campos da tela.",
      "Defina dias e horários permitidos antes de ampliar o volume.",
      "Clique em Atualizar; só use Executar tick agora para teste pontual e com cuidado.",
      "Clique em Salvar configurações no rodapé.",
      "Acompanhe respostas; se algo sair do esperado, clique para Desligado e abra o suporte com IA.",
    ],
    41,
  ),
  article(
    "reaquecimento",
    "Automações",
    "Reaqueça contatos parados",
    "Retomada controlada de leads frios (tela e/ou Agenda).",
    "/admin/reaquecimento",
    ["reaquecimento", "reativação", "followup", "frio", "grupo b"],
    [
      "Abra Agendamentos → Quem esfriou para reativar contatos.",
      "Escolha o grupo de contatos e o motivo da retomada.",
      "Revise a mensagem e os intervalos na tela.",
      "Comece com um grupo pequeno; evite disparo em massa no primeiro teste.",
      "Ative e acompanhe respostas no Histórico (Agendamentos → Histórico).",
      "Interrompa ou pause envios sem retorno quando a tela permitir.",
    ],
    42,
  ),
  article(
    "ligacao",
    "Automações",
    "Faça ligações pela plataforma",
    "Aba Ligação: Nova ligação, gravar/gerar áudio e iniciar.",
    "/admin?tab=voz",
    ["ligação", "voz", "telefone", "discador", "sms", "gravar"],
    [
      "No menu (Recursos), clique em Ligação.",
      "Abra a aba Nova ligação.",
      "Gere áudio com Gerar áudio Sofia (v3) ou clique em Gravar / Upload conforme a etapa do assistente.",
      "Avance com Continuar até revisar a base e o texto.",
      "Clique em Iniciar ligações só depois de conferir a lista e o áudio.",
      "Use as abas Bases, Não Perturbe, Programação do ciclo, SMS e Histórico para organizar e respeitar quem não quer contato.",
      "Leia a aba Ajuda dentro de Ligação (painel O que este módulo faz) se for a primeira vez.",
    ],
    43,
  ),
  article(
    "produtos",
    "Produtos e vendas",
    "Gerencie produtos e vendas",
    "Novo orçamento, pipeline e acompanhamento.",
    "/admin?tab=produtos",
    ["produto", "venda", "proposta", "orçamento", "pipeline"],
    [
      "No menu, clique em Produtos & Vendas.",
      "Use as abas: Acompanhamento, Orçamentos, Pipeline e Catálogo.",
      "Para criar: clique em Novo orçamento → preencha o sheet Criar orçamento → confirme.",
      "Acompanhe etapas no Pipeline; atualize conforme o avanço da venda.",
      "Em Acompanhamento, veja Oportunidades de venda cruzada → Configurar / Enviar no WhatsApp quando fizer sentido.",
      "Registre o motivo quando a venda não avançar, para não perder o histórico.",
    ],
    50,
    true,
  ),
  article(
    "solar",
    "Produtos e vendas",
    "Crie um estudo solar",
    "Endereço, telhado, painéis e salvar estudo para proposta.",
    "/admin/solar-design",
    ["solar", "telhado", "painel", "projeto", "economia"],
    [
      "Abra Projeto solar em /admin/solar-design.",
      "Informe o endereço e confirme no mapa / busca da tela.",
      "Revise a imagem do telhado e ajuste a quantidade de painéis.",
      "Salve o estudo.",
      "Volte em Produtos & Vendas / orçamento e use o estudo salvo na proposta quando a tela oferecer.",
    ],
    51,
  ),
  article(
    "parceiros",
    "Produtos e vendas",
    "Gerencie parceiros",
    "Cadastrar indicador, gerar link e acompanhar indicações.",
    "/admin?tab=parceiros",
    ["parceiro", "indicação", "rodízio", "qr code", "comissão"],
    [
      "No menu, clique em Parceiros.",
      "Clique em Novo Parceiro (ou Cadastrar primeiro parceiro se a lista estiver vazia).",
      "No diálogo Novo Parceiro Indicador, preencha nome e dados pedidos → clique em Criar Parceiro.",
      "Abra o parceiro criado e copie / gere o link exclusivo (e QR se disponível).",
      "Configure rodízio e notificações se a tela oferecer essas opções.",
      "Acompanhe os contatos atribuídos na própria área de Parceiros.",
    ],
    52,
  ),
  article(
    "financeiro",
    "Financeiro",
    "Entenda o Financeiro",
    "Abas Boletos, Recebíveis e Carteira Green — sempre confira o período.",
    "/admin?tab=financeiro",
    ["saldo", "carteira", "comissão", "recebíveis", "boletos", "pagamento"],
    [
      "No menu esquerdo, clique em Financeiro.",
      "Clique na aba Boletos, Recebíveis ou Carteira Green (Extrato pode aparecer para perfis admin).",
      "Ajuste o período / filtros no topo antes de comparar valores.",
      "Em Boletos, clique em um item da tabela para ver detalhes e ações de cobrança.",
      "Em Recebíveis ou Carteira Green, clique na movimentação para ver o detalhe.",
      "Se um valor confirmado não aparecer, atualize a página; se continuar errado, abra o suporte com IA e informe data e tipo (boleto/comissão/carteira).",
    ],
    60,
    true,
  ),
  article(
    "pos-venda",
    "Pós-venda",
    "Acompanhe o pós-venda",
    "Kanban de clientes ativos: análise, assinatura e 30–120 dias.",
    "/admin?tab=crm-clientes",
    ["pós-venda", "devolutiva", "assinatura", "aprovado", "30 dias"],
    [
      "No menu, clique em Clientes ativos.",
      "Filtre pela coluna / situação que precisa de atenção (em análise, aprovado, reprovado, 30/60/90/120 dias).",
      "Abra o cliente e revise pendências, datas e documentos.",
      "Resolva devolutivas antes de mover o card.",
      "Registre o contato feito (WhatsApp ou nota) para manter o histórico.",
      "Mensagens automáticas de pós-venda ficam em Agendamentos → Agenda → Pós-venda — revise antes de ampliar.",
    ],
    70,
  ),
  article(
    "academy",
    "Primeiros passos",
    "Aprenda na Academy",
    "Trilhas, aulas, anotações e provas.",
    "/admin?tab=academy",
    ["academy", "curso", "aula", "treinamento", "prova"],
    [
      "No menu (Recursos), clique em Academy.",
      "Escolha uma trilha ou aula na lista.",
      "Assista ao vídeo e use o caderno de anotações se aparecer o botão de notas.",
      "Faça a avaliação / prova quando estiver disponível.",
      "Seu progresso fica salvo — volte depois pela mesma trilha.",
    ],
    80,
  ),
  article(
    "conta-dados",
    "Conta e suporte",
    "Atualize seus dados da conta",
    "Nome, foto, ID iGreen e senha em Configurações.",
    "/admin?tab=dashboard",
    ["dados", "perfil", "configurações", "id igreen", "conta", "senha"],
    [
      "No topo do Painel, abra Configurações (engrenagem / menu da conta).",
      "Confira nome, telefone e foto do perfil.",
      "Confirme se o ID iGreen está correto (necessário para sincronização).",
      "Altere a senha pelo card de senha, se precisar.",
      "Salve as alterações e feche o painel de configurações.",
      "Volte ao Painel e confira se os dados aparecem atualizados.",
    ],
    91,
  ),
  article(
    "saude-bot",
    "Conta e suporte",
    "Veja a saúde do atendimento",
    "Alertas do atendimento automático e o que corrigir.",
    "/admin/saude-bot",
    ["saúde", "bot", "alerta", "diagnóstico", "atendimento"],
    [
      "Abra Saúde do atendimento em /admin/saude-bot.",
      "Leia os alertas em destaque (WhatsApp, fluxo, automação).",
      "Clique / siga o link da área indicada para corrigir (ex.: reconectar WhatsApp).",
      "Volte depois e confira se o alerta sumiu.",
      "Se o alerta persistir sem explicação clara, abra o suporte com IA com o texto do alerta.",
    ],
    92,
  ),
  article(
    "suporte",
    "Conta e suporte",
    "Peça ajuda ao suporte",
    "IA com dados da sua operação + histórico da conversa salvo.",
    "/ajuda?suporte=1",
    ["ajuda", "suporte", "erro", "problema", "humano", "ia"],
    [
      "Toque no botão verde de ajuda (?) no canto inferior direito.",
      "Clique em Perguntar ao suporte com IA.",
      "Descreva: o que queria fazer, em qual tela estava e qual botão clicou.",
      "Cole a mensagem de erro ou o nome da campanha/cliente se houver.",
      "Siga os passos numerados que a IA responder (ela usa seus dados reais de saldo e Meta quando disponíveis).",
      "A conversa fica salva; se precisar, limpe com o ícone de lixeira no topo do chat.",
      "Se a IA não resolver, peça encaminhamento ao suporte humano.",
    ],
    90,
    true,
  ),
];

const normalize = (value: string) => value.normalize("NFD").replace(/[\u0300-\u036f]/g, "").toLowerCase();

export function searchHelpCatalog(query: string, category = "all", source: HelpArticle[] = HELP_CATALOG) {
  const terms = normalize(query).split(/\s+/).filter(Boolean);
  return source
    .filter((item) => category === "all" || item.category === category)
    .map((item) => {
      const title = normalize(item.title);
      const haystack = normalize([item.title, item.summary, item.body, item.category, ...item.keywords].join(" "));
      const score = terms.reduce((total, term) => total + (title.includes(term) ? 5 : haystack.includes(term) ? 1 : 0), 0);
      return { item, score };
    })
    .filter(({ score }) => terms.length === 0 || score === terms.length || score > terms.length)
    .sort((a, b) => b.score - a.score || Number(b.item.featured) - Number(a.item.featured) || a.item.order_index - b.item.order_index)
    .map(({ item }) => item);
}

export function mergeHelpArticles(rows: TourArticle[], steps: TourStep[]): HelpArticle[] {
  const stepById = new Map(steps.map((step) => [step.id, step]));
  const dynamic = rows.map((row): HelpArticle => {
    const linked = row.related_tour_step_id ? stepById.get(row.related_tour_step_id) : undefined;
    const parsedSteps = row.body.split("\n").map((line) => line.replace(/^\s*\d+[.)-]?\s*/, "").trim()).filter(Boolean);
    return {
      ...row,
      summary: parsedSteps[0] || row.body.slice(0, 180),
      href: linked?.cta_href || linked?.route || "/admin",
      keywords: [row.category, row.title],
      steps: parsedSteps,
    };
  });
  const dynamicTitles = new Set(dynamic.map((item) => normalize(item.title)));
  return [...dynamic, ...HELP_CATALOG.filter((item) => !dynamicTitles.has(normalize(item.title)))];
}

/** Texto compacto para injetar no prompt da IA (edge functions). */
export function formatHelpCatalogForAi(source: HelpArticle[] = HELP_CATALOG): string {
  return source
    .map((item) => {
      const steps = item.steps.map((step, index) => `${index + 1}. ${step}`).join("\n");
      return `[${item.category}] ${item.title}\nResumo: ${item.summary}\nAbra: ${item.href}\n${steps}`;
    })
    .join("\n\n");
}
