-- ============================================================
-- [SUPERSEDED / NO-OP] Sistema de Comissões e Conversões
-- 2026-05-22
-- ============================================================
--
-- Esta migration foi CONSOLIDADA e SUBSTITUÍDA por:
--   20260531000009_add_commission_conversion_columns.sql
--
-- Motivo: a versão original criava `commission_rate` como `integer` com
-- check `IN (10,20,40,50,60,70,80,100)` e dois índices
-- (customers_converted_idx, customers_converted_campaign_idx). A versão
-- canônica (20260531000009) — que é a EFETIVAMENTE aplicada em produção —
-- usa `smallint` com check `BETWEEN 1 AND 100` e o índice
-- `idx_customers_converted`.
--
-- Esta migration NUNCA foi aplicada nesta base (não consta em
-- supabase_migrations.schema_migrations e seus índices/checks exclusivos
-- não existem no banco). Mantemos o arquivo como NO-OP apenas para
-- preservar o slot no histórico e evitar que um rebuild do zero
-- (supabase db reset / novo ambiente) crie as colunas com o tipo errado
-- ANTES da migration canônica, gerando divergência de schema.
--
-- Não adicione DDL aqui. Toda a definição de comissão/conversão vive em
-- 20260531000009_add_commission_conversion_columns.sql.

-- Intencionalmente vazio (no-op).
SELECT 1;
