// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zlzasfhcxcznaprrragl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpsemFzZmhjeGN6bmFwcnJyYWdsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzEyNzQ1NzAsImV4cCI6MjA4Njg1MDU3MH0.OJzRdi_Z_1TFZjQXmK8rJofBeHVZc27VSo2vMMw9Spo";

const SUPABASE_FETCH_TIMEOUT_MS = 15000;

/**
 * Em DEV, edge functions com CORS restrito (allowlist) quebram quando o Vite
 * sobe em localhost:8081/8082. O vite.config já tem `/functions-proxy` →
 * Supabase; reescrever a URL torna a chamada same-origin (sem preflight CORS).
 * Produção não é afetada (`import.meta.env.DEV` é false).
 */
function rewriteFunctionsUrlForDev(url: string): string {
  if (!import.meta.env.DEV) return url;
  return url.replace(
    /^https:\/\/zlzasfhcxcznaprrragl\.supabase\.co\/functions\/v1(?=\/|$)/,
    "/functions-proxy",
  );
}

const fetchWithTimeout: typeof fetch = async (input, init?: RequestInit) => {
  const controller = new AbortController();
  const timeout = window.setTimeout(() => controller.abort(), SUPABASE_FETCH_TIMEOUT_MS);
  const requestInit = init ?? {};

  try {
    let nextInput: RequestInfo | URL = input;
    if (typeof input === "string") {
      nextInput = rewriteFunctionsUrlForDev(input);
    } else if (input instanceof URL) {
      nextInput = new URL(rewriteFunctionsUrlForDev(input.href));
    } else if (typeof Request !== "undefined" && input instanceof Request) {
      const rewritten = rewriteFunctionsUrlForDev(input.url);
      if (rewritten !== input.url) {
        nextInput = new Request(rewritten, input);
      }
    }

    return await fetch(nextInput, {
      ...requestInit,
      signal: requestInit.signal ?? controller.signal,
    });
  } catch (error) {
    if (error instanceof DOMException && error.name === "AbortError") {
      throw new Error("A conexão com o servidor demorou demais. Tente novamente.");
    }
    throw error;
  } finally {
    window.clearTimeout(timeout);
  }
};

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  global: {
    fetch: fetchWithTimeout,
  },
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
    flowType: "pkce",
  }
});